/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as ReportsShipmentsRouteImport } from './routes/reports/shipments'
import { Route as ReportsSettlementsRouteImport } from './routes/reports/settlements'
import { Route as ReportsCouriersRouteImport } from './routes/reports/couriers'
import { Route as ReportsCompaniesRouteImport } from './routes/reports/companies'
import { Route as ReportsCollectionsRouteImport } from './routes/reports/collections'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTrackingRouteImport } from './routes/_authenticated/tracking'
import { Route as AuthenticatedStaffMembersRouteImport } from './routes/_authenticated/staff-members'
import { Route as AuthenticatedShipmentsRouteImport } from './routes/_authenticated/shipments'
import { Route as AuthenticatedSettlementsRouteImport } from './routes/_authenticated/settlements'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedReturnsRouteImport } from './routes/_authenticated/returns'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMobileRouteImport } from './routes/_authenticated/mobile'
import { Route as AuthenticatedGovernoratesRouteImport } from './routes/_authenticated/governorates'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedCouriersRouteImport } from './routes/_authenticated/couriers'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedCollectionsRouteImport } from './routes/_authenticated/collections'
import { Route as AuthenticatedCitiesRouteImport } from './routes/_authenticated/cities'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedApprovalsRouteImport } from './routes/_authenticated/approvals'
import { Route as AuthenticatedShipmentsIndexRouteImport } from './routes/_authenticated/shipments.index'
import { Route as AuthenticatedShipmentsOrderIdRouteImport } from './routes/_authenticated/shipments.$orderId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ReportsShipmentsRoute = ReportsShipmentsRouteImport.update({
  id: '/reports/shipments',
  path: '/reports/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSettlementsRoute = ReportsSettlementsRouteImport.update({
  id: '/reports/settlements',
  path: '/reports/settlements',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCouriersRoute = ReportsCouriersRouteImport.update({
  id: '/reports/couriers',
  path: '/reports/couriers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCompaniesRoute = ReportsCompaniesRouteImport.update({
  id: '/reports/companies',
  path: '/reports/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCollectionsRoute = ReportsCollectionsRouteImport.update({
  id: '/reports/collections',
  path: '/reports/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrackingRoute = AuthenticatedTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffMembersRoute =
  AuthenticatedStaffMembersRouteImport.update({
    id: '/staff-members',
    path: '/staff-members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShipmentsRoute = AuthenticatedShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettlementsRoute =
  AuthenticatedSettlementsRouteImport.update({
    id: '/settlements',
    path: '/settlements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReturnsRoute = AuthenticatedReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMobileRoute = AuthenticatedMobileRouteImport.update({
  id: '/mobile',
  path: '/mobile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGovernoratesRoute =
  AuthenticatedGovernoratesRouteImport.update({
    id: '/governorates',
    path: '/governorates',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCouriersRoute = AuthenticatedCouriersRouteImport.update({
  id: '/couriers',
  path: '/couriers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCollectionsRoute =
  AuthenticatedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCitiesRoute = AuthenticatedCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApprovalsRoute = AuthenticatedApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShipmentsIndexRoute =
  AuthenticatedShipmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedShipmentsRoute,
  } as any)
const AuthenticatedShipmentsOrderIdRoute =
  AuthenticatedShipmentsOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedShipmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/chat': typeof AuthenticatedChatRoute
  '/cities': typeof AuthenticatedCitiesRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/couriers': typeof AuthenticatedCouriersRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/governorates': typeof AuthenticatedGovernoratesRoute
  '/mobile': typeof AuthenticatedMobileRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/settlements': typeof AuthenticatedSettlementsRoute
  '/shipments': typeof AuthenticatedShipmentsRouteWithChildren
  '/staff-members': typeof AuthenticatedStaffMembersRoute
  '/tracking': typeof AuthenticatedTrackingRoute
  '/users': typeof AuthenticatedUsersRoute
  '/reports/collections': typeof ReportsCollectionsRoute
  '/reports/companies': typeof ReportsCompaniesRoute
  '/reports/couriers': typeof ReportsCouriersRoute
  '/reports/settlements': typeof ReportsSettlementsRoute
  '/reports/shipments': typeof ReportsShipmentsRoute
  '/reports/': typeof ReportsIndexRoute
  '/shipments/$orderId': typeof AuthenticatedShipmentsOrderIdRoute
  '/shipments/': typeof AuthenticatedShipmentsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/approvals': typeof AuthenticatedApprovalsRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/chat': typeof AuthenticatedChatRoute
  '/cities': typeof AuthenticatedCitiesRoute
  '/collections': typeof AuthenticatedCollectionsRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/couriers': typeof AuthenticatedCouriersRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/governorates': typeof AuthenticatedGovernoratesRoute
  '/mobile': typeof AuthenticatedMobileRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/settlements': typeof AuthenticatedSettlementsRoute
  '/staff-members': typeof AuthenticatedStaffMembersRoute
  '/tracking': typeof AuthenticatedTrackingRoute
  '/users': typeof AuthenticatedUsersRoute
  '/reports/collections': typeof ReportsCollectionsRoute
  '/reports/companies': typeof ReportsCompaniesRoute
  '/reports/couriers': typeof ReportsCouriersRoute
  '/reports/settlements': typeof ReportsSettlementsRoute
  '/reports/shipments': typeof ReportsShipmentsRoute
  '/': typeof AuthenticatedIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/shipments/$orderId': typeof AuthenticatedShipmentsOrderIdRoute
  '/shipments': typeof AuthenticatedShipmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/approvals': typeof AuthenticatedApprovalsRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/cities': typeof AuthenticatedCitiesRoute
  '/_authenticated/collections': typeof AuthenticatedCollectionsRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/couriers': typeof AuthenticatedCouriersRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/governorates': typeof AuthenticatedGovernoratesRoute
  '/_authenticated/mobile': typeof AuthenticatedMobileRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/returns': typeof AuthenticatedReturnsRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/settlements': typeof AuthenticatedSettlementsRoute
  '/_authenticated/shipments': typeof AuthenticatedShipmentsRouteWithChildren
  '/_authenticated/staff-members': typeof AuthenticatedStaffMembersRoute
  '/_authenticated/tracking': typeof AuthenticatedTrackingRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/reports/collections': typeof ReportsCollectionsRoute
  '/reports/companies': typeof ReportsCompaniesRoute
  '/reports/couriers': typeof ReportsCouriersRoute
  '/reports/settlements': typeof ReportsSettlementsRoute
  '/reports/shipments': typeof ReportsShipmentsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/_authenticated/shipments/$orderId': typeof AuthenticatedShipmentsOrderIdRoute
  '/_authenticated/shipments/': typeof AuthenticatedShipmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/approvals'
    | '/audit-log'
    | '/change-password'
    | '/chat'
    | '/cities'
    | '/collections'
    | '/companies'
    | '/couriers'
    | '/departments'
    | '/governorates'
    | '/mobile'
    | '/notifications'
    | '/profile'
    | '/returns'
    | '/roles'
    | '/settings'
    | '/settlements'
    | '/shipments'
    | '/staff-members'
    | '/tracking'
    | '/users'
    | '/reports/collections'
    | '/reports/companies'
    | '/reports/couriers'
    | '/reports/settlements'
    | '/reports/shipments'
    | '/reports/'
    | '/shipments/$orderId'
    | '/shipments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/approvals'
    | '/audit-log'
    | '/change-password'
    | '/chat'
    | '/cities'
    | '/collections'
    | '/companies'
    | '/couriers'
    | '/departments'
    | '/governorates'
    | '/mobile'
    | '/notifications'
    | '/profile'
    | '/returns'
    | '/roles'
    | '/settings'
    | '/settlements'
    | '/staff-members'
    | '/tracking'
    | '/users'
    | '/reports/collections'
    | '/reports/companies'
    | '/reports/couriers'
    | '/reports/settlements'
    | '/reports/shipments'
    | '/'
    | '/reports'
    | '/shipments/$orderId'
    | '/shipments'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/_authenticated/approvals'
    | '/_authenticated/audit-log'
    | '/_authenticated/change-password'
    | '/_authenticated/chat'
    | '/_authenticated/cities'
    | '/_authenticated/collections'
    | '/_authenticated/companies'
    | '/_authenticated/couriers'
    | '/_authenticated/departments'
    | '/_authenticated/governorates'
    | '/_authenticated/mobile'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/returns'
    | '/_authenticated/roles'
    | '/_authenticated/settings'
    | '/_authenticated/settlements'
    | '/_authenticated/shipments'
    | '/_authenticated/staff-members'
    | '/_authenticated/tracking'
    | '/_authenticated/users'
    | '/reports/collections'
    | '/reports/companies'
    | '/reports/couriers'
    | '/reports/settlements'
    | '/reports/shipments'
    | '/_authenticated/'
    | '/reports/'
    | '/_authenticated/shipments/$orderId'
    | '/_authenticated/shipments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReportsCollectionsRoute: typeof ReportsCollectionsRoute
  ReportsCompaniesRoute: typeof ReportsCompaniesRoute
  ReportsCouriersRoute: typeof ReportsCouriersRoute
  ReportsSettlementsRoute: typeof ReportsSettlementsRoute
  ReportsShipmentsRoute: typeof ReportsShipmentsRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/reports/shipments': {
      id: '/reports/shipments'
      path: '/reports/shipments'
      fullPath: '/reports/shipments'
      preLoaderRoute: typeof ReportsShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/settlements': {
      id: '/reports/settlements'
      path: '/reports/settlements'
      fullPath: '/reports/settlements'
      preLoaderRoute: typeof ReportsSettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/couriers': {
      id: '/reports/couriers'
      path: '/reports/couriers'
      fullPath: '/reports/couriers'
      preLoaderRoute: typeof ReportsCouriersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/companies': {
      id: '/reports/companies'
      path: '/reports/companies'
      fullPath: '/reports/companies'
      preLoaderRoute: typeof ReportsCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/collections': {
      id: '/reports/collections'
      path: '/reports/collections'
      fullPath: '/reports/collections'
      preLoaderRoute: typeof ReportsCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tracking': {
      id: '/_authenticated/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof AuthenticatedTrackingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff-members': {
      id: '/_authenticated/staff-members'
      path: '/staff-members'
      fullPath: '/staff-members'
      preLoaderRoute: typeof AuthenticatedStaffMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shipments': {
      id: '/_authenticated/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof AuthenticatedShipmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settlements': {
      id: '/_authenticated/settlements'
      path: '/settlements'
      fullPath: '/settlements'
      preLoaderRoute: typeof AuthenticatedSettlementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/returns': {
      id: '/_authenticated/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AuthenticatedReturnsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mobile': {
      id: '/_authenticated/mobile'
      path: '/mobile'
      fullPath: '/mobile'
      preLoaderRoute: typeof AuthenticatedMobileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/governorates': {
      id: '/_authenticated/governorates'
      path: '/governorates'
      fullPath: '/governorates'
      preLoaderRoute: typeof AuthenticatedGovernoratesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/couriers': {
      id: '/_authenticated/couriers'
      path: '/couriers'
      fullPath: '/couriers'
      preLoaderRoute: typeof AuthenticatedCouriersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/collections': {
      id: '/_authenticated/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AuthenticatedCollectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cities': {
      id: '/_authenticated/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof AuthenticatedCitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/approvals': {
      id: '/_authenticated/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AuthenticatedApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/shipments/': {
      id: '/_authenticated/shipments/'
      path: '/'
      fullPath: '/shipments/'
      preLoaderRoute: typeof AuthenticatedShipmentsIndexRouteImport
      parentRoute: typeof AuthenticatedShipmentsRoute
    }
    '/_authenticated/shipments/$orderId': {
      id: '/_authenticated/shipments/$orderId'
      path: '/$orderId'
      fullPath: '/shipments/$orderId'
      preLoaderRoute: typeof AuthenticatedShipmentsOrderIdRouteImport
      parentRoute: typeof AuthenticatedShipmentsRoute
    }
  }
}

interface AuthenticatedShipmentsRouteChildren {
  AuthenticatedShipmentsOrderIdRoute: typeof AuthenticatedShipmentsOrderIdRoute
  AuthenticatedShipmentsIndexRoute: typeof AuthenticatedShipmentsIndexRoute
}

const AuthenticatedShipmentsRouteChildren: AuthenticatedShipmentsRouteChildren =
  {
    AuthenticatedShipmentsOrderIdRoute: AuthenticatedShipmentsOrderIdRoute,
    AuthenticatedShipmentsIndexRoute: AuthenticatedShipmentsIndexRoute,
  }

const AuthenticatedShipmentsRouteWithChildren =
  AuthenticatedShipmentsRoute._addFileChildren(
    AuthenticatedShipmentsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedApprovalsRoute: typeof AuthenticatedApprovalsRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCitiesRoute: typeof AuthenticatedCitiesRoute
  AuthenticatedCollectionsRoute: typeof AuthenticatedCollectionsRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedCouriersRoute: typeof AuthenticatedCouriersRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedGovernoratesRoute: typeof AuthenticatedGovernoratesRoute
  AuthenticatedMobileRoute: typeof AuthenticatedMobileRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReturnsRoute: typeof AuthenticatedReturnsRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSettlementsRoute: typeof AuthenticatedSettlementsRoute
  AuthenticatedShipmentsRoute: typeof AuthenticatedShipmentsRouteWithChildren
  AuthenticatedStaffMembersRoute: typeof AuthenticatedStaffMembersRoute
  AuthenticatedTrackingRoute: typeof AuthenticatedTrackingRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedApprovalsRoute: AuthenticatedApprovalsRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCitiesRoute: AuthenticatedCitiesRoute,
  AuthenticatedCollectionsRoute: AuthenticatedCollectionsRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedCouriersRoute: AuthenticatedCouriersRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedGovernoratesRoute: AuthenticatedGovernoratesRoute,
  AuthenticatedMobileRoute: AuthenticatedMobileRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReturnsRoute: AuthenticatedReturnsRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSettlementsRoute: AuthenticatedSettlementsRoute,
  AuthenticatedShipmentsRoute: AuthenticatedShipmentsRouteWithChildren,
  AuthenticatedStaffMembersRoute: AuthenticatedStaffMembersRoute,
  AuthenticatedTrackingRoute: AuthenticatedTrackingRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReportsCollectionsRoute: ReportsCollectionsRoute,
  ReportsCompaniesRoute: ReportsCompaniesRoute,
  ReportsCouriersRoute: ReportsCouriersRoute,
  ReportsSettlementsRoute: ReportsSettlementsRoute,
  ReportsShipmentsRoute: ReportsShipmentsRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
