import type { ApprovalHistoryEntry, ApprovalRequest } from "@/lib/admin/approvals-types";

function minutesFromNow(minutes: number): string {
  return new Date(Date.now() + minutes * 60 * 1000).toISOString();
}

function hoursFromNow(hours: number): string {
  return new Date(Date.now() + hours * 60 * 60 * 1000).toISOString();
}

function daysAgo(days: number): string {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
}

export const APPROVAL_REQUESTS: ApprovalRequest[] = [
  {
    approval_request_id: "apr-001",
    ref: "APR-3201",
    order_id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
    internal_code: "MR-2841",
    shipping_company_id: "sc-001",
    company_name: "أرامكس مصر",
    approval_type: 1,
    original_amount: 275,
    requested_amount: 230,
    requested_by_id: "da-001",
    requested_by_name: "خالد العتيبي",
    reason: "اتفق العميل مع الراسل على خصم",
    approval_status: 1,
    expires_at: minutesFromNow(95),
    resolved_at: null,
    resolved_by: null,
    review_note: null,
    created_at: hoursFromNow(-2),
    updated_at: hoursFromNow(-2),
  },
  {
    approval_request_id: "apr-002",
    ref: "APR-3200",
    order_id: "e5f6a7b8-c9d0-1234-ef01-345678901234",
    internal_code: "MR-2836",
    shipping_company_id: "sc-005",
    company_name: "زاجل اكسبريس",
    approval_type: 2,
    original_amount: 455,
    requested_amount: 60,
    requested_by_id: "da-005",
    requested_by_name: "يوسف الغامدي",
    reason: "رفض العميل ودفع رسوم الشحن فقط",
    approval_status: 1,
    expires_at: minutesFromNow(18),
    resolved_at: null,
    resolved_by: null,
    review_note: null,
    created_at: hoursFromNow(-1),
    updated_at: hoursFromNow(-1),
  },
  {
    approval_request_id: "apr-007",
    ref: "APR-3202",
    order_id: "b8c9d0e1-f2a3-4567-1234-678901234567",
    internal_code: "MR-2834",
    shipping_company_id: "sc-001",
    company_name: "أرامكس مصر",
    approval_type: 3,
    original_amount: 1200,
    requested_amount: 600,
    requested_by_id: "da-006",
    requested_by_name: "ناصر الدوسري",
    reason: "تسليم جزئي — العميل استلم نصف الكمية",
    approval_status: 1,
    expires_at: minutesFromNow(240),
    resolved_at: null,
    resolved_by: null,
    review_note: null,
    created_at: minutesFromNow(-45),
    updated_at: minutesFromNow(-45),
  },
  {
    approval_request_id: "apr-003",
    ref: "APR-3199",
    order_id: "d4e5f6a7-b8c9-0123-def0-234567890123",
    internal_code: "MR-2838",
    shipping_company_id: "sc-004",
    company_name: "DHL Express",
    approval_type: 1,
    original_amount: 3210,
    requested_amount: 2950,
    requested_by_id: "da-004",
    requested_by_name: "فهد الشهري",
    reason: "تعديل سعر بعد موافقة العميل",
    approval_status: 2,
    expires_at: null,
    resolved_at: daysAgo(1),
    resolved_by: "مريم حسن",
    review_note: "تم التحقق مع الراسل — موافقة",
    created_at: daysAgo(2),
    updated_at: daysAgo(1),
  },
  {
    approval_request_id: "apr-004",
    ref: "APR-3198",
    order_id: "f6a7b8c9-d0e1-2345-f012-456789012345",
    internal_code: "MR-2835",
    shipping_company_id: "sc-002",
    company_name: "سمسا للشحن",
    approval_type: 3,
    original_amount: 780,
    requested_amount: 320,
    requested_by_id: "da-001",
    requested_by_name: "خالد العتيبي",
    reason: "تسليم جزئي — 2 من 4 قطع",
    approval_status: 3,
    expires_at: null,
    resolved_at: daysAgo(2),
    resolved_by: "مريم حسن",
    review_note: "الكمية المطلوبة غير متوافقة مع بوليصة الشحن",
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
  },
  {
    approval_request_id: "apr-005",
    ref: "APR-3197",
    order_id: "c3d4e5f6-a7b8-9012-cdef-123456789012",
    internal_code: "MR-2839",
    shipping_company_id: "sc-003",
    company_name: "بوسطة",
    approval_type: 2,
    original_amount: 560,
    requested_amount: 50,
    requested_by_id: "da-003",
    requested_by_name: "سعد القحطاني",
    reason: "—",
    approval_status: 4,
    expires_at: daysAgo(1),
    resolved_at: null,
    resolved_by: null,
    review_note: null,
    created_at: daysAgo(2),
    updated_at: daysAgo(1),
  },
  {
    approval_request_id: "apr-006",
    ref: "APR-3196",
    order_id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
    internal_code: "MR-2840",
    shipping_company_id: "sc-002",
    company_name: "سمسا للشحن",
    approval_type: 3,
    original_amount: 1420.5,
    requested_amount: 900,
    requested_by_id: "da-002",
    requested_by_name: "محمد الزهراني",
    reason: "تسليم جزئي — سماعات فقط",
    approval_status: 2,
    expires_at: null,
    resolved_at: hoursFromNow(-3),
    resolved_by: "مريم حسن",
    review_note: "موافقة على التحصيل الجزئي",
    created_at: hoursFromNow(-5),
    updated_at: hoursFromNow(-3),
  },
];

export const APPROVAL_HISTORY: ApprovalHistoryEntry[] = [
  {
    id: "ah-001",
    approval_request_id: "apr-001",
    ref: "APR-3201",
    action: "created",
    actor_id: "da-001",
    actor_name: "خالد العتيبي",
    actor_role: "agent",
    note: "اتفق العميل مع الراسل على خصم",
    from_status: null,
    to_status: 1,
    created_at: hoursFromNow(-2),
  },
  {
    id: "ah-002",
    approval_request_id: "apr-002",
    ref: "APR-3200",
    action: "created",
    actor_id: "da-005",
    actor_name: "يوسف الغامدي",
    actor_role: "agent",
    note: "رفض العميل ودفع رسوم الشحن فقط",
    from_status: null,
    to_status: 1,
    created_at: hoursFromNow(-1),
  },
  {
    id: "ah-003",
    approval_request_id: "apr-007",
    ref: "APR-3202",
    action: "created",
    actor_id: "da-006",
    actor_name: "ناصر الدوسري",
    actor_role: "agent",
    note: "تسليم جزئي — العميل استلم نصف الكمية",
    from_status: null,
    to_status: 1,
    created_at: minutesFromNow(-45),
  },
  {
    id: "ah-004",
    approval_request_id: "apr-003",
    ref: "APR-3199",
    action: "created",
    actor_id: "da-004",
    actor_name: "فهد الشهري",
    actor_role: "agent",
    note: null,
    from_status: null,
    to_status: 1,
    created_at: daysAgo(2),
  },
  {
    id: "ah-005",
    approval_request_id: "apr-003",
    ref: "APR-3199",
    action: "approved",
    actor_id: "usr-comp-102",
    actor_name: "مريم حسن",
    actor_role: "company",
    note: "تم التحقق مع الراسل — موافقة",
    from_status: 1,
    to_status: 2,
    created_at: daysAgo(1),
  },
  {
    id: "ah-006",
    approval_request_id: "apr-004",
    ref: "APR-3198",
    action: "created",
    actor_id: "da-001",
    actor_name: "خالد العتيبي",
    actor_role: "agent",
    note: null,
    from_status: null,
    to_status: 1,
    created_at: daysAgo(2),
  },
  {
    id: "ah-007",
    approval_request_id: "apr-004",
    ref: "APR-3198",
    action: "rejected",
    actor_id: "usr-comp-102",
    actor_name: "مريم حسن",
    actor_role: "company",
    note: "الكمية المطلوبة غير متوافقة مع بوليصة الشحن",
    from_status: 1,
    to_status: 3,
    created_at: daysAgo(2),
  },
  {
    id: "ah-008",
    approval_request_id: "apr-005",
    ref: "APR-3197",
    action: "created",
    actor_id: "da-003",
    actor_name: "سعد القحطاني",
    actor_role: "agent",
    note: null,
    from_status: null,
    to_status: 1,
    created_at: daysAgo(2),
  },
  {
    id: "ah-009",
    approval_request_id: "apr-005",
    ref: "APR-3197",
    action: "expired",
    actor_id: "system",
    actor_name: "النظام",
    actor_role: "admin",
    note: "انتهت مهلة الرد دون إجراء من الشركة",
    from_status: 1,
    to_status: 4,
    created_at: daysAgo(1),
  },
  {
    id: "ah-010",
    approval_request_id: "apr-006",
    ref: "APR-3196",
    action: "created",
    actor_id: "da-002",
    actor_name: "محمد الزهراني",
    actor_role: "agent",
    note: null,
    from_status: null,
    to_status: 1,
    created_at: hoursFromNow(-5),
  },
  {
    id: "ah-011",
    approval_request_id: "apr-006",
    ref: "APR-3196",
    action: "approved",
    actor_id: "usr-comp-102",
    actor_name: "مريم حسن",
    actor_role: "company",
    note: "موافقة على التحصيل الجزئي",
    from_status: 1,
    to_status: 2,
    created_at: hoursFromNow(-3),
  },
];

export const APPROVAL_AGENT_OPTIONS = [
  { value: "da-001", label: "خالد العتيبي" },
  { value: "da-002", label: "محمد الزهراني" },
  { value: "da-004", label: "فهد الشهري" },
  { value: "da-005", label: "يوسف الغامدي" },
  { value: "da-003", label: "سعد القحطاني" },
  { value: "da-006", label: "ناصر الدوسري" },
];

export const APPROVAL_COMPANY_OPTIONS = [
  { value: "sc-001", label: "أرامكس مصر" },
  { value: "sc-002", label: "سمسا للشحن" },
  { value: "sc-003", label: "بوسطة" },
  { value: "sc-004", label: "DHL Express" },
  { value: "sc-005", label: "زاجل اكسبريس" },
];

export const MOCK_COMPANY_REVIEWER = {
  id: "usr-comp-102",
  name: "مريم حسن",
  company_id: "sc-002",
};
