import type { NotificationPreferencesState, NotificationRecord } from "@/lib/admin/notifications-types";
import { getDefaultPreferences } from "@/lib/admin/notifications-types";

function minutesAgo(minutes: number): string {
  return new Date(Date.now() - minutes * 60 * 1000).toISOString();
}

function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();
}

function daysAgo(days: number): string {
  return new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
}

export const NOTIFICATIONS: NotificationRecord[] = [
  {
    notification_id: "ntf-001",
    notification_type: 1,
    channel: "in_app",
    title: "شحنة جديدة MR-2841",
    body: "تم استلام شحنة من شركة أرامكس مصر — بانتظار التعيين",
    reference_code: "MR-2841",
    action_url: "/shipments",
    action_label: "عرض الشحنة",
    is_read: 0,
    read_at: null,
    sent_at: minutesAgo(2),
    push_status: null,
    device_hint: null,
    created_at: minutesAgo(2),
  },
  {
    notification_id: "ntf-002",
    notification_type: 2,
    channel: "push",
    title: "المندوب خالد العتيبي متاح",
    body: "أصبح المندوب متاحاً في منطقة مدينة نصر",
    reference_code: "da-001",
    action_url: "/couriers",
    action_label: "عرض المندوب",
    is_read: 0,
    read_at: null,
    sent_at: minutesAgo(5),
    push_status: "delivered",
    device_hint: "Chrome · Windows",
    created_at: minutesAgo(5),
  },
  {
    notification_id: "ntf-003",
    notification_type: 3,
    channel: "in_app",
    title: "تحصيل جديد 1,420.50 ج.م",
    body: "تم تسجيل تحصيل COD من مندوب محمد الزهراني — MR-2840",
    reference_code: "col-001",
    action_url: "/collections",
    action_label: "عرض التحصيل",
    is_read: 0,
    read_at: null,
    sent_at: minutesAgo(12),
    push_status: null,
    device_hint: null,
    created_at: minutesAgo(12),
  },
  {
    notification_id: "ntf-004",
    notification_type: 4,
    channel: "push",
    title: "طلب موافقة APR-3201",
    body: "تعديل سعر لطلب MR-2841 — بانتظار رد الشركة خلال 95 د",
    reference_code: "APR-3201",
    action_url: "/approvals",
    action_label: "مراجعة الطلب",
    is_read: 0,
    read_at: null,
    sent_at: minutesAgo(38),
    push_status: "delivered",
    device_hint: "Safari · iPhone",
    created_at: minutesAgo(38),
  },
  {
    notification_id: "ntf-005",
    notification_type: 1,
    channel: "push",
    title: "تم تسليم MR-2790",
    body: "المندوب: خالد العتيبي — العميل: أحمد محمد",
    reference_code: "MR-2790",
    action_url: "/shipments",
    action_label: "عرض الشحنة",
    is_read: 1,
    read_at: hoursAgo(1),
    sent_at: hoursAgo(1),
    push_status: "delivered",
    device_hint: "Chrome · Windows",
    created_at: hoursAgo(1),
  },
  {
    notification_id: "ntf-006",
    notification_type: 1,
    channel: "in_app",
    title: "تأخر شحنة MR-2755",
    body: "تجاوزت الشحنة المدة المتوقعة للتسليم — يرجى المتابعة",
    reference_code: "MR-2755",
    action_url: "/shipments",
    action_label: "متابعة الشحنة",
    is_read: 1,
    read_at: hoursAgo(2),
    sent_at: hoursAgo(2),
    push_status: null,
    device_hint: null,
    created_at: hoursAgo(2),
  },
  {
    notification_id: "ntf-007",
    notification_type: 5,
    channel: "in_app",
    title: "تسوية أسبوعية جاهزة STL-1041",
    body: "تسوية سمسا للشحن — 7,974.00 ج.م بانتظار الدفع",
    reference_code: "STL-1041",
    action_url: "/settlements",
    action_label: "عرض التسوية",
    is_read: 1,
    read_at: daysAgo(1),
    sent_at: daysAgo(1),
    push_status: null,
    device_hint: null,
    created_at: daysAgo(1),
  },
  {
    notification_id: "ntf-008",
    notification_type: 6,
    channel: "push",
    title: "مرتجع جديد RTN-0521",
    body: "مرتجع من مندوب خالد العتيبي — MR-2835 بانتظار الاستلام",
    reference_code: "RTN-0521",
    action_url: "/returns",
    action_label: "عرض المرتجع",
    is_read: 0,
    read_at: null,
    sent_at: minutesAgo(20),
    push_status: "sent",
    device_hint: "Chrome · Android",
    created_at: minutesAgo(20),
  },
  {
    notification_id: "ntf-009",
    notification_type: 7,
    channel: "in_app",
    title: "تحديث النظام v2.4",
    body: "تم نشر تحسينات على لوحة التحكم والتتبع المباشر",
    reference_code: null,
    action_url: "/settings",
    action_label: "الإعدادات",
    is_read: 1,
    read_at: daysAgo(1),
    sent_at: daysAgo(1),
    push_status: null,
    device_hint: null,
    created_at: daysAgo(1),
  },
  {
    notification_id: "ntf-010",
    notification_type: 4,
    channel: "push",
    title: "موافقة عاجلة APR-3200",
    body: "طلب رسوم شحن — ينتهي خلال 18 دقيقة",
    reference_code: "APR-3200",
    action_url: "/approvals",
    action_label: "مراجعة فورية",
    is_read: 0,
    read_at: null,
    sent_at: minutesAgo(8),
    push_status: "delivered",
    device_hint: "Safari · iPhone",
    created_at: minutesAgo(8),
  },
  {
    notification_id: "ntf-011",
    notification_type: 3,
    channel: "push",
    title: "استلام نقد من مندوب",
    body: "محمد الزهراني — 980.00 ج.م بانتظار التسليم للإدارة",
    reference_code: "col-006",
    action_url: "/collections",
    action_label: "تسجيل الاستلام",
    is_read: 0,
    read_at: null,
    sent_at: minutesAgo(15),
    push_status: "failed",
    device_hint: "Chrome · Windows",
    created_at: minutesAgo(15),
  },
  {
    notification_id: "ntf-012",
    notification_type: 5,
    channel: "push",
    title: "تسوية معتمدة STL-1036",
    body: "تسوية مندوب فهد الشهري — 1,978.00 ج.م بانتظار الدفع",
    reference_code: "STL-1036",
    action_url: "/settlements",
    action_label: "عرض التسوية",
    is_read: 1,
    read_at: hoursAgo(3),
    sent_at: hoursAgo(4),
    push_status: "delivered",
    device_hint: "Chrome · Windows",
    created_at: hoursAgo(4),
  },
];

export const DEFAULT_PREFERENCES: NotificationPreferencesState = getDefaultPreferences();
